import Homepage from "@/components/website/Homepage";
import { ladiesProducts, menProducts } from "@/services/HomePageAPI";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default async function Home() {
  const getMenProducts = await menProducts();
  const getLadiesProducts = await ladiesProducts();

  return (
    <>
      <Homepage menData={getMenProducts} ladiesData={getLadiesProducts} />
    </>
  );
}
