import Homepage from "@/components/website/Homepage";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Homepage />
    </>
  );
}
